### ISSUE TITLE
[BUG]Program crash down with exception WinRing OLS_DRIVER_NOT_LOADED

### ISSUE THREAD

**Issue by 6543x1** [JamesCJ60/Universal-x86-Tuning-Utility#243]
**bug**
The program runs ok until last saturday it has not start with my system.I reinstall the uxtu but it's still unable to run the program(the icon will show a very short time and disapper soon)，the log is below:
```
2024-09-15 23:47:20.499 +08:00 [INF] Application started. Press Ctrl+C to shut down.
2024-09-15 23:47:20.539 +08:00 [INF] Hosting environment: Production
2024-09-15 23:47:20.541 +08:00 [INF] Content root path: C:\Program Files\JamesCJ60\Universal x86 Tuning Utility
2024-09-15 23:47:20.546 +08:00 [FTL] Unhandled dispatcher exception
System.TypeInitializationException: The type initializer for 'RyzenSmu.SMUCommands' threw an exception.
 ---> System.ApplicationException: WinRing OLS_DRIVER_NOT_LOADED
   at RyzenSmu.Smu..ctor(Boolean EnableDebug) in C:\Users\james\source\repos\Universal-x86-Tuning-Utility\Universal x86 Tuning Utility\Scripts\AMD Backend\RyzenSmu.cs:line 406
   at RyzenSmu.SMUCommands..cctor() in C:\Users\james\source\repos\Universal-x86-Tuning-Utility\Universal x86 Tuning Utility\Scripts\AMD Backend\RyzenSmu.cs:line 339
   --- End of inner exception stack trace ---
   at RyzenSmu.Addresses.Socket_FP6_AM4() in C:\Users\james\source\repos\Universal-x86-Tuning-Utility\Universal x86 Tuning Utility\Scripts\AMD Backend\RyzenSmu.cs:line 99
   at RyzenSmu.Addresses.setAddresses() in C:\Users\james\source\repos\Universal-x86-Tuning-Utility\Universal x86 Tuning Utility\Scripts\AMD Backend\RyzenSmu.cs:line 33
   at Universal_x86_Tuning_Utility.Scripts.Family.setCpuFamily() in C:\Users\james\source\repos\Universal-x86-Tuning-Utility\Universal x86 Tuning Utility\Scripts\Family.cs:line 159
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
I tried to uninstall the system updates installed recently but it did not work.
**To Reproduce**
Steps to reproduce the behaviour:
1. click uxtu.exe
2. it crash down on my computer

**My computer details**
CPU: AMD Ryzen 4800H
System: Windows 10 22H2
Memory:16GB DDR4
GPU:RTX 2060 Laptop

**Comment by 6543x1** [comment]
this problem has been solved, i closed LenovoPCManager, and the UXTU runs! I close the auto start of LenovoPCManager, and reboot system, the uxtu can start well on system boot. I don't know why this fxxk lenovo software will crash with UXTU(some days ago everything is good),.
This software is provided only with Chinese sold Lenovo PC.I closed the security function on this software but did not work, the way to solve is to close this fxxk software or uninstall it.
**In a word, close or uninstall all security software will work.**
To Chinese who find this--请关掉联想电脑管家，并关掉开机自启动！就是这个狗屎软件导致UXTU没法启动的，我也不知道为什么；如果还不行，就关掉所有的杀毒软件再试试，包括Windows自己的。
