### ISSUE TITLE
[BUG]crash when opening 

### ISSUE THREAD

**Issue by snpdzk** [JamesCJ60/Universal-x86-Tuning-Utility#251]
screenshot：
![image](https://github.com/user-attachments/assets/67131351-d573-4742-b712-d924831173c5)

cpu：2690v3
motherboard：hsgm x99-cf4

 - OS Version:  Windows 10 22H2 19045.5011

**Additional context**
logs：
2024-10-09 13:19:52.245 +08:00 [INF] Application started. Press Ctrl+C to shut down.
2024-10-09 13:19:52.281 +08:00 [INF] Hosting environment: Production
2024-10-09 13:19:52.282 +08:00 [INF] Content root path: C:\software\uxtu2
2024-10-09 13:19:52.283 +08:00 [FTL] Unhandled dispatcher exception
System.ArgumentOutOfRangeException: Index and length must refer to a location within the string. (Parameter 'length')
   at System.String.ThrowSubstringArgumentOutOfRange(Int32 startIndex, Int32 length)
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Universal_x86_Tuning_Utility.Scripts.Intel_Backend.Intel_Management.DetermineIntelMCHBAR() in C:\Users\james\source\repos\Universal-x86-Tuning-Utility\Universal x86 Tuning Utility\Scripts\Intel Backend\Intel_Management.cs:line 268
   at Universal_x86_Tuning_Utility.Scripts.Intel_Backend.Intel_Management.determineCPU() in C:\Users\james\source\repos\Universal-x86-Tuning-Utility\Universal x86 Tuning Utility\Scripts\Intel Backend\Intel_Management.cs:line 251
   at Universal_x86_Tuning_Utility.Scripts.Family.setCpuFamily() in C:\Users\james\source\repos\Universal-x86-Tuning-Utility\Universal x86 Tuning Utility\Scripts\Family.cs:line 97
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by JamesCJ60** [comment]
Hi, please ensure you are using the latest drivers from your hardware vendors and that you have installed all software prerequisites for UXTU.
