### ISSUE TITLE
[BUG]Cannot start software anymore

### ISSUE THREAD

**Issue by Yur3k1** [JamesCJ60/Universal-x86-Tuning-Utility#90]
Worked fine at first boot of the software but wont start anymore. Getting the same result after clean install of the software.

-----------------------------------------------------------------------------------------------------------------------------------------
Application: Universal x86 Tuning Utility Handheld.exe
CoreCLR Version: 7.0.823.31807
.NET Version: 7.0.8
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at Universal_x86_Tuning_Utility_Handheld.Services.AdaptivePresetManager.GetPreset(String presetName) in C:\Users\james\source\repos\Universal x86 Tuning Utility Handheld\Universal x86 Tuning Utility Handheld\Services\AdaptivePresetManager.cs:line 55
   at Universal_x86_Tuning_Utility_Handheld.App.OnStartup(Object sender, StartupEventArgs e) in C:\Users\james\source\repos\Universal x86 Tuning Utility Handheld\Universal x86 Tuning Utility Handheld\App.xaml.cs:line 241
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at Universal_x86_Tuning_Utility_Handheld.App.Main()

-----------------------------------------------------------------------------------------------------------------------------------------

Faulting application name: Universal x86 Tuning Utility Handheld.exe, version: 0.0.4.0, time stamp: 0x646e274e
Faulting module name: KERNELBASE.dll, version: 10.0.22621.1778, time stamp: 0x63f72683
Exception code: 0xe0434352
Fault offset: 0x000000000006536c
Faulting process id: 0x0x1634
Faulting application start time: 0x0x1D9AE7A1FB20D93
Faulting application path: C:\Program Files\JamesCJ\Universal x86 Tuning Utility Handheld\Universal x86 Tuning Utility Handheld.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 44cce0ca-c85e-4ed1-8885-156adaf6877a
Faulting package full name: 
Faulting package-relative application ID:

**Comment by Seeger0216** [comment]
how do you resolve this problem?
